# Generated by Django 4.0.6 on 2022-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_members_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='idnumber',
            field=models.IntegerField(null=True),
        ),
    ]
