# Generated by Django 4.0.6 on 2022-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_members_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
